[managers.system]
items = [
    "ninja",
    "gcc",
    "cmake",
    "meson",
    "libxcb",
    "xcb-proto",
    "xcb-util",
    "xcb-util-keysyms",
    "libxfixes",
    "libx11",
    "libxcomposite",
    "xorg-xinput",
    "libxrender",
    "pixman",
    "wayland-protocols",
    "cairo",
    "pango",
    "seatd",
    "libxkbcommon",
    "xcb-util-wm",
    "xorg-xwayland",
    "libinput",
    "libliftoff",
    "libdisplay-info",
    "cpio",
    "tomlplusplus",
    "xcur2png",
    "xdg-desktop-portal-hyprland-git",
    "xdg-desktop-portal-gtk",
    "hyprland-git",
    "hypridle-git",
    "hyprland-protocols-git",
    "hyprland-qt-support-git",
    "hyprpicker-git",
    "hyprlock-git",
    "hyprpaper-git",
    "hyprcursor-git",
    "uwsm",
    "aquamarine-git",
    "hyprpicker-git",
    "hyprlang-git",
    "hyprutils-git",
    "hyprwayland-scanner-git",
    "hyprland-guiutils-git",
    "hyprgraphics-git",
]
