[managers.system]
items = [
    "waydroid",
    "waydroid-script-git",
    "jadx",
    "python-frida",
    "python-frida-tools",
    "android-backup-extractor",
]

[managers.uvx]
items = [
    # "objection",
    "reflutter",
]

[managers.pip]
items = [
    "objection",
]

[managers.systemd-system]
items = [
    "waydroid-container",
]
